## This configuration was generated by terraform-provider-oci

resource oci_core_boot_volume_backup export_Terraform_Full03_05 {
  boot_volume_id = oci_core_instance.export_GL_Terraform.boot_volume_id
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-04T14:22:28.886Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "Terraform_Full03_05"
  freeform_tags = {
  }
  #source_details = <<Optional value not found in discovery>>
  type = "FULL"
}

resource oci_core_instance_configuration export_instance-config-gl {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2020-11-12T14:07:55.945Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "instance-config-gl"
  freeform_tags = {
  }
  instance_details {
    instance_type = "compute"
    launch_details {
      agent_config {
        #are_all_plugins_disabled = <<Optional value not found in discovery>>
        is_management_disabled = "false"
        is_monitoring_disabled = "false"
      }
      availability_config {
        recovery_action = "RESTORE_INSTANCE"
      }
      #availability_domain = <<Optional value not found in discovery>>
      compartment_id = var.compartment_ocid
      create_vnic_details {
        assign_public_ip = "true"
        defined_tags = {
          "TagDefaults.Created_at" = "2020-11-12T14:06:43.323Z"
          "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
        }
        display_name = "Ubuntu1"
        freeform_tags = {
        }
        #hostname_label = <<Optional value not found in discovery>>
        nsg_ids = [
        ]
        #private_ip = <<Optional value not found in discovery>>
        skip_source_dest_check = "false"
        #subnet_id = <<Optional value not found in discovery>>
      }
      #dedicated_vm_host_id = <<Optional value not found in discovery>>
      defined_tags = {
        "TagDefaults.Created_at" = "2020-11-12T14:06:43.092Z"
        "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
      }
      display_name = "Ubuntu1"
      extended_metadata = {
      }
      #fault_domain = <<Optional value not found in discovery>>
      freeform_tags = {
      }
      instance_options {
        are_legacy_imds_endpoints_disabled = "false"
      }
      #ipxe_script = <<Optional value not found in discovery>>
      is_pv_encryption_in_transit_enabled = "false"
      launch_mode                         = "NATIVE"
      launch_options {
        boot_volume_type = ""
        firmware         = ""
        #is_consistent_volume_naming_enabled = <<Optional value not found in discovery>>
        #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
        network_type            = "VFIO"
        remote_data_volume_type = ""
      }
      metadata = {
        "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFuvFTBgNVZjCTvvSbMPQGQq8YZcHBeT1JOi1wLKP6QCAs7ppk2AuNSf3LhM8Cthk0xEIeNvmFdalCfZfOVzzpcRCUq3RXaen3z1Od42/5MZKb9WdpCuOhZBjJGTiDRcYaJfEcGvY8tsUoZK+6fs974W94v/ie5uneZTbFf0rEEn9utm+LFVZ90rZ/qTwgrB9C0JTZ0h/vksECJpHA71kjUOPdAL7vPBMVQn5DHQAOANf/t6Dm1ljDwHGIhq261yE8m/640cf3iQ1wrYTVbGp62ClQJZDCNtxyuCqQbBYICpe+SIJiehIG85m08gfIjAcZS2SMkmJof4jAbslR8o70zJPkIDOaHWKc3stmYoRtl+Q0GzMw+UydUrWzx83sNewgBG1ciEoHc/sAaFjcJI6l7K4E1sAc8ExZHKS63r2WSHhRGQckF3wob2XeVbatlj2JrkMTnud03NXKTXj6KPPjS9p1I9ArdbLYk0FNl6AbrKYiB5y4ESINgl5jJ52HqTU="
      }
      #platform_config = <<Optional value not found in discovery>>
      preferred_maintenance_action = "REBOOT"
      shape                        = "VM.Standard.E3.Flex"
      shape_config {
        memory_in_gbs = "16"
        ocpus         = "1"
      }
      source_details {
        #boot_volume_id = <<Optional value not found in discovery>>
        #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
        image_id    = "ocid1.image.oc1.iad.aaaaaaaanoalk3fhpbocojo3wma5e3xrye5yestrujevos44ol42a2lqzhba"
        source_type = "image"
      }
    }
  }
  #instance_id = <<Optional value not found in discovery>>
  #source = <<Optional value not found in discovery>>
}

resource oci_core_instance export_GL_Terraform {
  agent_config {
    are_all_plugins_disabled = "false"
    is_management_disabled   = "false"
    is_monitoring_disabled   = "false"
    plugins_config {
      desired_state = "ENABLED"
      name          = "OS Management Service Agent"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Custom Logs Monitoring"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Run Command"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Monitoring"
    }
  }
  availability_config {
    recovery_action = "RESTORE_INSTANCE"
  }
  availability_domain = data.oci_identity_availability_domain.export_UWQV-US-ASHBURN-AD-1.name
  compartment_id      = var.compartment_ocid
  create_vnic_details {
    assign_public_ip = "true"
    defined_tags = {
      "TagDefaults.Created_at" = "2021-03-04T14:22:29.109Z"
      "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
    }
    display_name = "GL_Terraform"
    freeform_tags = {
    }
    hostname_label = "gl-terraform"
    nsg_ids = [
    ]
    private_ip             = "10.0.0.36"
    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.export_Public-Subnet-GLVCN.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  #dedicated_vm_host_id = <<Optional value not found in discovery>>
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-04T14:22:28.886Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "GL_Terraform"
  extended_metadata = {
  }
  fault_domain = "FAULT-DOMAIN-3"
  freeform_tags = {
  }
  instance_options {
    are_legacy_imds_endpoints_disabled = "false"
  }
  #ipxe_script = <<Optional value not found in discovery>>
  #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
  launch_options {
    boot_volume_type                    = "PARAVIRTUALIZED"
    firmware                            = "UEFI_64"
    is_consistent_volume_naming_enabled = "true"
    is_pv_encryption_in_transit_enabled = "false"
    network_type                        = "VFIO"
    remote_data_volume_type             = "PARAVIRTUALIZED"
  }
  metadata = {
    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKmi5khhGNsfpvfJ1Kt01nIEMnq6T4UKLkI74Lu9iUs25SYcIvHTlUJqwEDi1QBKCDorR1a7pSsctb2dmjrJHslvCLrWav2obxRxU7YIt06oQv7P9WANSFhCBT71VOtMqoiGF/lyHguYsSXIfKrAzC187gvNgKu/0DjQP8RNsmzJJeXdN3I6CSQ+K4wEUjmMbAHyDFC00LGJ4u7CaGT3xqPmMesoId7jHHmsXtTSQjNR/PpeKzuHTUSxUBbbBttXqcJIlOjVS10359Dk/yBQLDeGFE322dRa308xVXO3HcBVq+6kmb00vLVXfNte5S2JhrBvST2TSLVFtgaE5gZwUB ssh-key-2021-03-04"
  }
  #preserve_boot_volume = <<Optional value not found in discovery>>
  shape = "VM.Standard.E3.Flex"
  shape_config {
    memory_in_gbs = "16"
    ocpus         = "1"
  }
  source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    #kms_key_id = <<Optional value not found in discovery>>
    source_id   = var.export_GL_Terraform_source_image_id
    source_type = "image"
  }
  state = "RUNNING"
}

resource oci_core_internet_gateway export_Internet-Gateway-GLVCN {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2020-09-21T19:39:12.637Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "Internet Gateway-GLVCN"
  enabled      = "true"
  freeform_tags = {
    "VCN" = "VCN-2020-09-21T19:37:38"
  }
  vcn_id = oci_core_vcn.export_GLVCN.id
}

resource oci_core_public_ip export_IP-for-NAT-gateway-ocid1-natgateway-oc1-iad-aaaaaaaas2yh6h3zemenfdiriwf6itloedjhbeanjm6pcepgmebjttebrkwa {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2020-09-21T19:39:13.702Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "IP for NAT gateway: ocid1.natgateway.oc1.iad.aaaaaaaas2yh6h3zemenfdiriwf6itloedjhbeanjm6pcepgmebjttebrkwa"
  freeform_tags = {
    "VCN" = "VCN-2020-09-21T19:37:38"
  }
  lifetime = "EPHEMERAL"
  #private_ip_id = <<Optional value not found in discovery>>
  #public_ip_pool_id = <<Optional value not found in discovery>>
}

resource oci_core_service_gateway export_Service-Gateway-GLVCN {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2020-09-21T19:39:12.758Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "Service Gateway-GLVCN"
  freeform_tags = {
    "VCN" = "VCN-2020-09-21T19:37:38"
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = "ocid1.service.oc1.iad.aaaaaaaam4zfmy2rjue6fmglumm3czgisxzrnvrwqeodtztg7hwa272mlfna"
  }
  vcn_id = oci_core_vcn.export_GLVCN.id
}

resource oci_core_subnet export_Private-Subnet-GLVCN {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.1.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2020-09-21T19:39:12.641Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  dhcp_options_id = oci_core_vcn.export_GLVCN.default_dhcp_options_id
  display_name    = "Private Subnet-GLVCN"
  dns_label       = "sub09211939021"
  freeform_tags = {
    "VCN" = "VCN-2020-09-21T19:37:38"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_Route-Table-for-Private-Subnet-GLVCN.id
  security_list_ids = [
    oci_core_security_list.export_Security-List-for-Private-Subnet-GLVCN.id,
  ]
  vcn_id = oci_core_vcn.export_GLVCN.id
}

resource oci_core_subnet export_Public-Subnet-GLVCN {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.0.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2020-09-21T19:39:12.632Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  dhcp_options_id = oci_core_vcn.export_GLVCN.default_dhcp_options_id
  display_name    = "Public Subnet-GLVCN"
  dns_label       = "sub09211939020"
  freeform_tags = {
    "VCN" = "VCN-2020-09-21T19:37:38"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_GLVCN.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_GLVCN.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_GLVCN.id
}

resource oci_core_private_ip export_GL_Terraform_1 {
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-04T14:22:29.109Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "GL_Terraform"
  freeform_tags = {
  }
  hostname_label = "gl-terraform"
  ip_address     = "10.0.0.36"
  #vlan_id = <<Optional value not found in discovery>>
  vnic_id = "ocid1.vnic.oc1.iad.abuwcljrj2ep27246ihkcho6yyusj2kn4ff72lnzve75drf672mgebxx2ota"
}

resource oci_core_vcn export_simple-vcn {
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-04T16:46:11.088Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "simple-vcn"
  dns_label    = "vcn1"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  #is_ipv6enabled = <<Optional value not found in discovery>>
}

resource oci_core_vcn export_GLVCN {
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2020-09-21T19:39:11.738Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "GLVCN"
  dns_label    = "glvcn"
  freeform_tags = {
    "VCN" = "VCN-2020-09-21T19:37:38"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  #is_ipv6enabled = <<Optional value not found in discovery>>
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-simple-vcn {
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-04T16:46:11.088Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "Default DHCP Options for simple-vcn"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_simple-vcn.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "vcn1.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_default_route_table export_Default-Route-Table-for-simple-vcn {
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-04T16:46:11.088Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "Default Route Table for simple-vcn"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.export_simple-vcn.default_route_table_id
}

resource oci_core_default_security_list export_Default-Security-List-for-simple-vcn {
  defined_tags = {
    "TagDefaults.Created_at" = "2021-03-04T16:46:11.088Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "Default Security List for simple-vcn"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_simple-vcn.default_security_list_id
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-GLVCN {
  defined_tags = {
    "TagDefaults.Created_at" = "2020-09-21T19:39:11.738Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "Default DHCP Options for GLVCN"
  freeform_tags = {
    "VCN" = "VCN-2020-09-21T19:37:38"
  }
  manage_default_resource_id = oci_core_vcn.export_GLVCN.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "glvcn.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_nat_gateway export_NAT-Gateway-GLVCN {
  block_traffic  = "false"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2020-09-21T19:39:12.670Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "NAT Gateway-GLVCN"
  freeform_tags = {
    "VCN" = "VCN-2020-09-21T19:37:38"
  }
  public_ip_id = oci_core_public_ip.export_IP-for-NAT-gateway-ocid1-natgateway-oc1-iad-aaaaaaaas2yh6h3zemenfdiriwf6itloedjhbeanjm6pcepgmebjttebrkwa.id
  vcn_id       = oci_core_vcn.export_GLVCN.id
}

resource oci_core_route_table export_Route-Table-for-Private-Subnet-GLVCN {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2020-09-21T19:39:12.630Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "Route Table for Private Subnet-GLVCN"
  freeform_tags = {
    "VCN" = "VCN-2020-09-21T19:37:38"
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_NAT-Gateway-GLVCN.id
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "all-iad-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.export_Service-Gateway-GLVCN.id
  }
  vcn_id = oci_core_vcn.export_GLVCN.id
}

resource oci_core_default_route_table export_Default-Route-Table-for-GLVCN {
  defined_tags = {
    "TagDefaults.Created_at" = "2020-09-21T19:39:11.738Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "Default Route Table for GLVCN"
  freeform_tags = {
    "VCN" = "VCN-2020-09-21T19:37:38"
  }
  manage_default_resource_id = oci_core_vcn.export_GLVCN.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_Internet-Gateway-GLVCN.id
  }
}

resource oci_core_security_list export_Security-List-for-Private-Subnet-GLVCN {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2020-09-21T19:39:12.899Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "Security List for Private Subnet-GLVCN"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "VCN-2020-09-21T19:37:38"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "For FSS"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      #max = <<Optional value not found in discovery>>
      #min = <<Optional value not found in discovery>>
      source_port_range {
        max = "111"
        min = "111"
      }
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "For FSS"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      #max = <<Optional value not found in discovery>>
      #min = <<Optional value not found in discovery>>
      source_port_range {
        max = "2048"
        min = "2048"
      }
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "For FSS"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      #max = <<Optional value not found in discovery>>
      #min = <<Optional value not found in discovery>>
      source_port_range {
        max = "2049"
        min = "2049"
      }
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "For FSS"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      #max = <<Optional value not found in discovery>>
      #min = <<Optional value not found in discovery>>
      source_port_range {
        max = "2050"
        min = "2050"
      }
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_GLVCN.id
}

resource oci_core_default_security_list export_Default-Security-List-for-GLVCN {
  defined_tags = {
    "TagDefaults.Created_at" = "2020-09-21T19:39:11.738Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/giuseppe.lino@oracle.com"
  }
  display_name = "Default Security List for GLVCN"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "For FSS"
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "111"
      min = "111"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "For FSS"
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "2048"
      min = "2048"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "For FSS"
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "2049"
      min = "2049"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "For FSS"
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "false"
    tcp_options {
      max = "2050"
      min = "2050"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  egress_security_rules {
    description      = "For FSS"
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "17"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    udp_options {
      max = "111"
      min = "111"
      #source_port_range = <<Optional value not found in discovery>>
    }
  }
  freeform_tags = {
    "VCN" = "VCN-2020-09-21T19:37:38"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "For FSS"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "111"
      min = "111"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "For FSS"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "2048"
      min = "2048"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "For FSS"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "2049"
      min = "2049"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "For FSS"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "2050"
      min = "2050"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "For FSS"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "17"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    udp_options {
      max = "111"
      min = "111"
      #source_port_range = <<Optional value not found in discovery>>
    }
  }
  ingress_security_rules {
    description = "For FSS"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "17"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    udp_options {
      max = "2048"
      min = "2048"
      #source_port_range = <<Optional value not found in discovery>>
    }
  }
  manage_default_resource_id = oci_core_vcn.export_GLVCN.default_security_list_id
}

